export let Films = [
    {id: 1, Title: '365 Days',Year: '2022',Nation: 'USA', img:'assets/images/365 Days.jpg',info:'The life of Laura, a simple sales director, changes when she takes a trip to Sicily but gets kidnapped by Massimo, a mafia member. Massimo keeps her hostage for 365 days to make her fall for him.'},
    {id: 2, Title: 'Batman',Year: '2022', Nation: 'USA', img:'assets/images/Batman.jpg',info:'Batman is a superhero appearing in American comic books published by DC Comics. The character was created by artist Bob Kane and writer Bill Finger, and debuted in the 27th issue of the comic book Detective Comics on March 30, 1939.'},
    {id: 3, Title: 'Day Shift', Year: '2019',Nation: 'Australian', img:'assets/images/Day_Shift_(film).jpg',info:'A hardworking dad out to provide for his daughter uses a boring pool-cleaning job as a front for his real gig: hunting and killing vampires.'},
    {id: 4, Title: 'Drifting Home', Year: '2022',Nation: 'USA',img:'assets/images/Drifting Home.jpg',info:'During summer break, sixth graders Kosuke and Natsume play in an apartment building set to be demolished. They find themselves caught up in a strange phenomenon. All they can see around them is a vast sea.'},
    {id: 5, Title: 'Incantation', Year: '2022',Nation: 'British',img:'assets/images/Incantation.jpg' ,info:'Six years ago, Li Ronan is cursed after breaking a religious taboo; now, she must protect her daughter from the consequences of her actions.'},
    {id: 6, Title: 'Jurassic World Domination', Year: '2022',Nation: 'USA', img:'assets/images/Jurassic World Dominion.jpg',info:'From Jurassic World architect and director Colin Trevorrow, Dominion takes place four years after Isla Nublar has been destroyed. Dinosaurs now live - and hunt - alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with historys most fearsome creatures.'},
    {id: 7, Title: 'The Lost City', Year: '2023',Nation: 'HongKong', img:'assets/images/The Lost City.jpg',info:'Reclusive author Loretta Sage writes about exotic places in her popular adventure novels that feature a handsome cover model named Alan. While on tour promoting her new book with Alan, Loretta gets kidnapped by an eccentric billionaire who hopes she can lead him to an ancient citys lost treasure '},
    {id: 8, Title: 'Top Gun 2', Year: '2013',Nation: 'USA', img:'assets/images/Top Gun 2.jpg',info:'After more than 30 years of service as one of the Navy"s top aviators, Pete "Maverick" Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him. '},
    {id: 9, Title: 'Us', Year: '2018',Nation: 'VietNam', img:'assets/images/Us_(2019)_theatrical_poster.png',info:'Adelaide Wilson and her family are attacked by mysterious figures dressed in red. Upon closer inspection, the Wilsons realise that the intruders are exact lookalikes of them.'}
]